name: Build PDF
on: [push]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test for trailing whitespace
        uses: harupy/find-trailing-whitespace@master
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: thesis.pdf
          path: thesis.pdf
          if-no-files-found: error